name: Go CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        go-version: ['1.24', '1.25']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies (libc and libm are already available)
      run: |
        # Verify libc and libm are available (should be present by default)
        ldconfig -p | grep libc.so || echo "libc not found"
        ldconfig -p | grep libm.so || echo "libm not found"

    - name: Build
      run: go build -v

    - name: Run tests
      run: go test -v ./...

    - name: Run integration tests
      run: go test -v -run TestFlapPrograms
