name: Go CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.25']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install SDL3 and Raylib5
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libsdl3-dev raylib
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install sdl3 raylib
        fi
      shell: bash

    - name: Build
      run: go build -v

    - name: Run all tests
      run: go test -v ./...
