name: Go CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.25']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install SDL3
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libsdl3-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install sdl3
        fi
      shell: bash

    - name: Install Raylib5 (optional)
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          brew install raylib || true
        elif [ "$RUNNER_OS" == "Linux" ]; then
          # Try to install from PPA, but don't fail if unavailable
          sudo add-apt-repository -y ppa:texus/raylib || true
          sudo apt-get update || true
          sudo apt-get install -y libraylib5-dev || true
        fi
      shell: bash
      continue-on-error: true

    - name: Build
      run: go build -v

    - name: Run all tests
      run: go test -v ./...
